require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AlbumArtistsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AlbumArtist. As you add validations to AlbumArtist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlbumArtistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all album_artists as @album_artists" do
      album_artist = AlbumArtist.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:album_artists)).to eq([album_artist])
    end
  end

  describe "GET show" do
    it "assigns the requested album_artist as @album_artist" do
      album_artist = AlbumArtist.create! valid_attributes
      get :show, {:id => album_artist.to_param}, valid_session
      expect(assigns(:album_artist)).to eq(album_artist)
    end
  end

  describe "GET new" do
    it "assigns a new album_artist as @album_artist" do
      get :new, {}, valid_session
      expect(assigns(:album_artist)).to be_a_new(AlbumArtist)
    end
  end

  describe "GET edit" do
    it "assigns the requested album_artist as @album_artist" do
      album_artist = AlbumArtist.create! valid_attributes
      get :edit, {:id => album_artist.to_param}, valid_session
      expect(assigns(:album_artist)).to eq(album_artist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlbumArtist" do
        expect {
          post :create, {:album_artist => valid_attributes}, valid_session
        }.to change(AlbumArtist, :count).by(1)
      end

      it "assigns a newly created album_artist as @album_artist" do
        post :create, {:album_artist => valid_attributes}, valid_session
        expect(assigns(:album_artist)).to be_a(AlbumArtist)
        expect(assigns(:album_artist)).to be_persisted
      end

      it "redirects to the created album_artist" do
        post :create, {:album_artist => valid_attributes}, valid_session
        expect(response).to redirect_to(AlbumArtist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved album_artist as @album_artist" do
        post :create, {:album_artist => invalid_attributes}, valid_session
        expect(assigns(:album_artist)).to be_a_new(AlbumArtist)
      end

      it "re-renders the 'new' template" do
        post :create, {:album_artist => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested album_artist" do
        album_artist = AlbumArtist.create! valid_attributes
        put :update, {:id => album_artist.to_param, :album_artist => new_attributes}, valid_session
        album_artist.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested album_artist as @album_artist" do
        album_artist = AlbumArtist.create! valid_attributes
        put :update, {:id => album_artist.to_param, :album_artist => valid_attributes}, valid_session
        expect(assigns(:album_artist)).to eq(album_artist)
      end

      it "redirects to the album_artist" do
        album_artist = AlbumArtist.create! valid_attributes
        put :update, {:id => album_artist.to_param, :album_artist => valid_attributes}, valid_session
        expect(response).to redirect_to(album_artist)
      end
    end

    describe "with invalid params" do
      it "assigns the album_artist as @album_artist" do
        album_artist = AlbumArtist.create! valid_attributes
        put :update, {:id => album_artist.to_param, :album_artist => invalid_attributes}, valid_session
        expect(assigns(:album_artist)).to eq(album_artist)
      end

      it "re-renders the 'edit' template" do
        album_artist = AlbumArtist.create! valid_attributes
        put :update, {:id => album_artist.to_param, :album_artist => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested album_artist" do
      album_artist = AlbumArtist.create! valid_attributes
      expect {
        delete :destroy, {:id => album_artist.to_param}, valid_session
      }.to change(AlbumArtist, :count).by(-1)
    end

    it "redirects to the album_artists list" do
      album_artist = AlbumArtist.create! valid_attributes
      delete :destroy, {:id => album_artist.to_param}, valid_session
      expect(response).to redirect_to(album_artists_url)
    end
  end

end
